[package]
name = "wayvr-ipc"
version = "0.1.0"
edition = "2024"
description = "IPC for controlling WayVR"
license = "MIT"
authors = ["galister", "oo8dev"]
repository = "https://github.com/wlx-team/wayvr"

[dependencies]
anyhow.workspace = true
bytes.workspace = true
log.workspace = true
serde.workspace = true
smallvec.workspace = true

# client-only deps
interprocess = { workspace = true, features = ["tokio"], optional = true }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros"], optional = true }
tokio-util = { version = "0.7.13", optional = true }

[features]
default = ["client"]
client = ["dep:interprocess", "dep:tokio", "dep:tokio-util"]
