[package]
name = "wgui"
version = "0.1.0"
edition = "2024"
description = "A VR-first Vulkan GUI library"
license = "GPL-3.0-only"
authors = ["galister", "oo8dev"]
repository = "https://github.com/wlx-team/wayvr"

[dependencies]
anyhow.workspace = true
glam.workspace = true
log.workspace = true
regex.workspace = true
rust-embed.workspace = true
serde_json.workspace = true
slotmap.workspace = true
smallvec.workspace = true
vulkano.workspace = true
vulkano-shaders.workspace = true

cosmic-text = "0.19.0"
etagere = "0.2.15"
flate2 = "1.1.5"
image = {
  version = "0.25.9",
  default-features = false,
  features = [
    "gif",
    "jpeg",
    "png",
    "rayon",
    "webp",
  ]
}
lru = "0.16.2"
ouroboros = "0.18.5"
parking_lot = "0.12.5"
resvg = { version = "0.45.1", default-features = false }
roxmltree = "0.21.1"
rustc-hash = "2.1.1"
taffy = "0.12.1"

# `video` wgui feature
bytes = { workspace = true, optional = true }
dav1d-sys = {
  git = "https://github.com/rust-av/dav1d-rs.git",
  rev = "03477a36c3de4f2aacbab81a8951150ffdb9c4c3",
  optional = true
}

[features]
default = ["video"]
video = ["dep:bytes", "dep:dav1d-sys"]
